---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-operator-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: mbconnect-secret-store
    kind: ClusterSecretStore
  target:
    name: datadog-operator-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: datadog-operator-secrets
