---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: mbc-infrastructure-shared
spec:
  interval: 10m0s
  chart:
    spec:
      chart: datadog-operator
      sourceRef:
        kind: HelmRepository
        name: datadog-helm
      version: ~1.3.0
  values:
    datadogCRDS:
      crds:
        datadogAgents: false
        datadogMetrics: false
        datadogMonitors: true
    datadogMonitor:
      enabled: true
    dd_url: https://app.datadoghq.eu
    logLevel: debug
    containerSecurityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 10000
      runAsGroup: 10000
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
  valuesFrom:
    - kind: Secret
      name: datadog-operator-secrets
      valuesKey: api-key
      targetPath: apiKey
    - kind: Secret
      name: datadog-operator-secrets
      valuesKey: app-key
      targetPath: appKey
